### ISSUE TITLE
penalty_alpha_mu must be scalar?

### ISSUE THREAD

**Issue by drisso** [drisso/archive-zinbwave#10]
The setValidity() of the object checks that penalty_alpha_mu is scalar.

However, penalty_alpha_mu is defined in the following way (here: https://github.com/drisso/zinb/blob/feature/S4/R/helper_methods.R#L152)

``` r
        if (!missing(penalty_alpha_mu)) {
            .Object@penalty_alpha_mu <- penalty_alpha_mu
        } else {
            val <- max(1, NROW(.Object@alpha_mu)*NCOL(.Object@alpha_mu))
            .Object@penalty_alpha_mu <- rep(1/val,NROW(.Object@alpha_mu))
        }
```

which is a vector of length NROW(alpha_mu).

@jpvert can you please tell me if I'm missing something?

**Comment by drisso** [comment]
It used to check that the length of penalty_alpha_mu was the same as the rows of alpha_mu, but it was change to check for a scalar in commit 6bccb1959a879e1c09c92ed457b7a5bc7df2b523 by @jpvert.

An analogous problem can be seen for penalty_alpha_pi.

**Comment by jpvert** [comment]
My mistake. I initially considered vectors for penalty_alpha_mu and penalty_alpha_pi to allow for different penalties on different columns, but after second thoughts I think it does not make much sense and it would make the orthogonalization procedure wrong. So I changed my mind to a single scalar instead of a vector. Alas I forgot to change the initialization, so the line [https://github.com/drisso/zinb/blob/feature/S4/R/helper_methods.R#L156](url):
`.Object@penalty_alpha_mu <- rep(1/val,NROW(.Object@alpha_mu))`
should be replaced by
`.Object@penalty_alpha_mu <- 1/val`

and same thing for penalty_alpha_mu in [https://github.com/drisso/zinb/blob/feature/S4/R/helper_methods.R#L174](url)

@drisso can you do it? thanks

**Comment by drisso** [comment]
Done!
