### ISSUE TITLE
In model2.pdf penalties should be vectors not scalars

### ISSUE THREAD

**Issue by drisso** [drisso/archive-zinbwave#20]

**Comment by jpvert** [comment]
I simplified the description of the model and the codes regarding penalties (and they should be coherent with each other).
I propose we just have scalars for epsilon_alpha_mu, epsilon_beta_mu etc..., as described in the paper. Then it is understood that all columns of the corresponding matrices are penalized by this scalar, except the intercept. The methods get_epsilon_alpha_mu() etc... output a vector of penalties, constant except perhaps in the first coordinate if there is an intercept.
I found it simpler and probably enough for most users. Note that in the case of W, alpha_mu and alpha_pi, it is important to have the same penalties for all columns otherwise the orthogonalization step and trace norm interpretation are not valid anymore.
